// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLDBApp.Data;

#nullable disable

namespace SQLDBApp.Migrations
{
    [DbContext(typeof(DevSqlDBContext))]
    partial class DevSqlDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SQLDBApp.Models.DataItems.DataItemCatg", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("C1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CatgCL")
                        .HasColumnType("int");

                    b.Property<string>("CatgID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FullPathId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCollectedHRef")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrvId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataItemCatg");
                });

            modelBuilder.Entity("SQLDBApp.Models.DataItems.DataItemCatgPerProd", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("DataItemCatgPerProdId")
                        .HasColumnType("bigint");

                    b.Property<string>("Href1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Href7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name7")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataItemCatgPerProd");
                });

            modelBuilder.Entity("SQLDBApp.Models.DataItems.DataItemPics", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("DataItemPicsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlHtml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataItemPics");
                });

            modelBuilder.Entity("SQLDBApp.Models.DataItems.DataItemPrices", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BackOrderTill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DataItemPricesId")
                        .HasColumnType("bigint");

                    b.Property<string>("DateLastInStock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateOfferExp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsBackOrdered")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOutOfStock")
                        .HasColumnType("bit");

                    b.Property<string>("OfferInfoHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PriceBuyCurrent")
                        .HasColumnType("float");

                    b.Property<double?>("PriceBuyDef")
                        .HasColumnType("float");

                    b.Property<double?>("PriceSellCurrent")
                        .HasColumnType("float");

                    b.Property<double?>("PriceSellDef")
                        .HasColumnType("float");

                    b.Property<double?>("PriceSellMax")
                        .HasColumnType("float");

                    b.Property<double?>("PriceSellMin")
                        .HasColumnType("float");

                    b.Property<string>("StateTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZipCodeTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DataItemPrices");
                });

            modelBuilder.Entity("SQLDBApp.Models.DataItems.DataItemProduct", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("DateLastAvail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateOfferExp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighlightsHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HowManyRatings")
                        .HasColumnType("int");

                    b.Property<int>("HowManyStars")
                        .HasColumnType("int");

                    b.Property<string>("ImgMain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgsGalleryHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAllBackOrdered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCollectedFull")
                        .HasColumnType("bit");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfferInfoHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PriceBuyCurrent")
                        .HasColumnType("float");

                    b.Property<double?>("PriceBuyCurrentAdv")
                        .HasColumnType("float");

                    b.Property<double?>("PriceBuyDef")
                        .HasColumnType("float");

                    b.Property<double?>("PriceBuyDefAdv")
                        .HasColumnType("float");

                    b.Property<double?>("PriceSellMax")
                        .HasColumnType("float");

                    b.Property<double?>("PriceSellMin")
                        .HasColumnType("float");

                    b.Property<long>("Product")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductOptionsHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortProdUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationsHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataItemProduct");
                });

            modelBuilder.Entity("SQLDBApp.Models.DataItems.DataItemSpecs", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("DataItemSpecsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Html")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DataItemSpecs");
                });
#pragma warning restore 612, 618
        }
    }
}
